all:
	$(MAKE) -f Makefile.main02 all

main02Build:
	$(MAKE) -f Makefile.main02 all


main02Run:
	$(MAKE) -f Makefile.main02 run

clean:
	$(MAKE) -f Makefile.main02 clean

fclean:
	$(MAKE) -f Makefile.main02 fclean

re: fclean all

.PHONY: all main02Build main02Run clean fclean re
