all:
	$(MAKE) -f Makefile.testCProgram all

testCProgramBuild:
	$(MAKE) -f Makefile.testCProgram all


testCProgramRun:
	$(MAKE) -f Makefile.testCProgram run

clean:
	$(MAKE) -f Makefile.testCProgram clean

fclean:
	$(MAKE) -f Makefile.testCProgram fclean

re: fclean all

.PHONY: all testCProgramBuild testCProgramRun clean fclean re
