LINK_COMPILER = gcc
LINK_FLAGS = -Wall -g3 -O0 -MMD -MP
ARGS = 
BIN = main02.out
SRCS = main2.c one.c subfolder/two.c
OBJS = main2.o one.o subfolder/two.o
DEPS = $(OBJS:.o=.d)

all: $(BIN)

$(BIN): $(OBJS)
	$(LINK_COMPILER) $(LINK_FLAGS) $^ -o $@

%.o: %.c
	gcc -Wall -g3 -O0 -MMD -MP -c $< -o $@

run: $(BIN)
	./$(BIN) $(ARGS)

clean:
	rm -f $(OBJS) $(DEPS)

fclean: clean
	rm -f $(BIN)

re: fclean all

.PHONY: all run clean fclean re

-include $(DEPS)
