all:
	$(MAKE) -f Makefile.main01 all

main01Build:
	$(MAKE) -f Makefile.main01 all


main01Run:
	$(MAKE) -f Makefile.main01 run

clean:
	$(MAKE) -f Makefile.main01 clean

fclean:
	$(MAKE) -f Makefile.main01 fclean

re: fclean all

.PHONY: all main01Build main01Run clean fclean re
